"""
Django settings for sornedir project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@c$u8)2up-sw@fr)0mwfa3h_9@62eqvm#x+o$)#e%x$a%^ra1x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
        #KULLANDIĞIM EKLENTİLER
    'ckeditor', 
    'django_cleanup',
    'stdimage',
    'crispy_forms',
    'captcha',
    #OLUŞTURDUĞUM UYGULAMALAR
    #'main',
    'uye',
    'icerikler',
    'pageviews',
]

AUTH_USER_MODEL = 'uye.Profile'
CRISPY_TEMPLATE_PACK = 'bootstrap3'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'pageviews.middleware.PageViewCounterMiddleware'
]

ROOT_URLCONF = 'sornedir.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ os.path.join(BASE_DIR, 'views'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'asw.context_processors.icerikler'
            ],
        },
    },
]

WSGI_APPLICATION = 'sornedir.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': 'localhost',
        'PORT': '',
        'USER': 'root',
        'PASSWORD': '',
        'NAME': 'sornedir_db'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'tr'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATICFILES_DIRS = [ os.path.join(BASE_DIR, "static/") ]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'statics/ ')

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CKEDITOR_JQUERY_URL = os.path.join(STATIC_URL, 'js/jquery-3.2.1.min.js')
CKEDITOR_UPLOAD_PATH = os.path.join( MEDIA_ROOT, 'uploads/' )
CKEDITOR_IMAGE_BACKEND = "Pillow"
CKEDITOR_CONFIGS = {
    'default': {
        #'skin': 'moono',
        # 'skin': 'office2013',
        'toolbar_Basic': [
            ['Source', '-', 'Bold', 'Italic']
        ],
        'toolbar_YourCustomToolbarConfig': [
            {'name': 'document', 'items': ['Maximize', 'Source']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll']},
            '/',
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'basicstyles',
             'items': [ 'Bold', 
                        'Italic', 
                        'Underline', 
                        'Link', 
                        'Unlink',
                        'Image', 
                        'HorizontalRule',
                        """'Subscript', 'Superscript',""" 
                        'RemoveFormat']},
            {'name': 'styles', 'items': ['FontSize']},
            {'name': 'paragraph',
             'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', '-',
                       'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock']}
            
            
        ],
        'toolbar': 'YourCustomToolbarConfig',  # put selected toolbar config here
        # 'toolbarGroups': [{ 'name': 'document', 'groups': [ 'mode', 'document', 'doctools' ] }],
         'height': 200,
         'width': '100%', 
        # 'filebrowserWindowHeight': 725,
        # 'filebrowserWindowWidth': 940,
        # 'toolbarCanCollapse': True,
        # 'mathJaxLib': '//cdn.mathjax.org/mathjax/2.2-latest/MathJax.js?config=TeX-AMS_HTML',
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            #'uploadimage', # the upload image feature
            # your extra plugins here
            #'div',
            'autolink',
            #'autoembed',
            'embedsemantic',
            #'autogrow',
            # 'devtools',
            #'widget',
            #'lineutils',
            #'clipboard',
            #'dialog',
            #'dialogui',
            #'elementspath'
        ]),
    }
}


RECAPTCHA_PUBLIC_KEY = '6Le-L0AUAAAAADmb870GW5M2_n6eQ3vyxydY1w1x'
RECAPTCHA_PRIVATE_KEY = '6Le-L0AUAAAAALZXQ865kUGY55-4tje56_GXvhME'
RECAPTCHA_PROXY = 'http://127.0.0.1:8000'
NOCAPTCHA = True

#AUTH_PROFILE_MODULE = 'uye.Extra'


from django.contrib import admin
admin.site.site_header = 'Sor Nedir Yönetim Paneli'
admin.site.site_title = 'Sor Nedir?'



