# Generated by Django 2.0.1 on 2018-02-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Eklenme')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('url', models.CharField(max_length=2000, verbose_name='Url')),
                ('counter', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
            ],
        ),
    ]
