# Generated by Django 2.0.1 on 2018-01-15 08:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevaplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Cevap')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('status', models.BooleanField(default=True, verbose_name='Yayında')),
                ('like', models.IntegerField(default=0, verbose_name='Beğeni')),
                ('best_answer', models.BooleanField(default=False, verbose_name='En İyi Cevap')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Gizli Kullanıcı Olarak Cevapla')),
                ('ip', models.CharField(blank=True, editable=False, max_length=40, verbose_name='Ip Adresi')),
                ('parent', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='icerikler.Cevaplar', verbose_name='Üst Cevap')),
            ],
            options={
                'verbose_name': 'Cevap',
                'verbose_name_plural': 'Cevaplar',
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Etiketler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Etiket')),
                ('seo_title', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Etiket Kısa İsmi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.BooleanField(default=True, verbose_name='Yayımla')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Kategoriler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kategori')),
                ('seo_title', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Kategori Kısa İsmi')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.BooleanField(default=True, verbose_name='Yayımla')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Sorular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Soru Başlığı')),
                ('seo_title', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Soru Kısa İsmi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Soru Detayları')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('u_time', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('views', models.IntegerField(default=0, verbose_name='Okunma')),
                ('like', models.IntegerField(default=0, verbose_name='Beğeni')),
                ('anonymous', models.BooleanField(default=False, verbose_name='Gizli Kullanıcı Olarak Sor')),
                ('status', models.BooleanField(default=True, verbose_name='Soruyu Yayımla')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='Gizli Kullanıcı Cevaplarını Kabul Et')),
                ('allow_private_message', models.BooleanField(default=True, verbose_name='Özel Cevapları Kabul Et')),
                ('ip', models.CharField(blank=True, editable=False, max_length=40, verbose_name='Ip Adresi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='icerikler.Kategoriler', verbose_name='Kategori')),
                ('tags', models.ManyToManyField(blank=True, to='icerikler.Etiketler', verbose_name='Etiketler')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to=settings.AUTH_USER_MODEL, verbose_name='Soran')),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'db_table': 'questions',
            },
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to='icerikler.Sorular', verbose_name='Soru'),
        ),
        migrations.AddField(
            model_name='cevaplar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to=settings.AUTH_USER_MODEL, verbose_name='Cevaplayan'),
        ),
    ]
