# Generated by Django 2.0.1 on 2018-01-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0005_remove_cevaplar_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cevaplar',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='icerikler.Cevaplar', verbose_name='Üst Cevap'),
        ),
    ]
