# Generated by Django 2.0.1 on 2018-02-04 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0007_auto_20180201_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='icerikler.Cevaplar', verbose_name='Üst Cevap'),
        ),
    ]
