# Generated by Django 2.0.1 on 2018-02-23 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icerikler', '0008_auto_20180205_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cevap_Oylari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True, verbose_name='Oy')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevap_oylari', to='icerikler.Cevaplar', verbose_name='Cevap')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevap_oylari', to=settings.AUTH_USER_MODEL, verbose_name='Oylayan')),
            ],
            options={
                'verbose_name': 'Cevap Oyu',
                'verbose_name_plural': 'Cevap Oyları',
                'db_table': 'answer_votes',
            },
        ),
        migrations.CreateModel(
            name='Soru_Oylari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(default=True, verbose_name='Oy')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soru_oylari', to='icerikler.Sorular', verbose_name='Soru')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soru_oylari', to=settings.AUTH_USER_MODEL, verbose_name='Oylayan')),
            ],
            options={
                'verbose_name': 'Soru Oyu',
                'verbose_name_plural': 'Soru Oyları',
                'db_table': 'question_votes',
            },
        ),
    ]
