# Generated by Django 2.0.1 on 2018-02-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0010_auto_20180224_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sorular',
            name='a_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Son Cevap'),
        ),
    ]
