# Generated by Django 2.0.1 on 2018-01-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategoriler',
            name='seo_title',
            field=models.SlugField(blank=True, editable=False, max_length=255, verbose_name='Kategori Kısa İsmi'),
        ),
    ]
