# Generated by Django 2.0.1 on 2018-01-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0004_auto_20180131_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cevaplar',
            name='parent',
        ),
    ]
