# Generated by Django 2.0.1 on 2018-01-31 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0006_cevaplar_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cevaplar',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alt_cevaplar', to='icerikler.Cevaplar', verbose_name='Üst Cevap'),
        ),
    ]
