# Generated by Django 2.0.1 on 2018-02-24 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('icerikler', '0009_cevap_oylari_soru_oylari'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategoriler',
            name='photo',
            field=stdimage.models.StdImageField(blank=True, upload_to='category-images', verbose_name='Kategori Görseli'),
        ),
        migrations.AlterField(
            model_name='cevap_oylari',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icerikler.Cevaplar', verbose_name='Cevap'),
        ),
        migrations.AlterField(
            model_name='cevap_oylari',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oylayan'),
        ),
        migrations.AlterField(
            model_name='soru_oylari',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icerikler.Sorular', verbose_name='Soru'),
        ),
        migrations.AlterField(
            model_name='soru_oylari',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Oylayan'),
        ),
    ]
