# Generated by Django 2.0.1 on 2018-01-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uye', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meslekler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Meslek Adı')),
                ('status', models.NullBooleanField(default=True, verbose_name='Görüntülenebilir')),
            ],
            options={
                'verbose_name': 'Meslek',
                'verbose_name_plural': 'Meslekler',
                'db_table': 'meslekler',
            },
        ),
    ]
