# Generated by Django 2.0.1 on 2018-01-13 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uye', '0002_meslekler'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meslek', to='uye.Meslekler', verbose_name='Meslek'),
        ),
    ]
